### ISSUE TITLE
potential working collaboratively 

### ISSUE THREAD

**Issue by alex-zige** [eproxus/opsworks#1]
Good work mate. Actually I was thinking about doing a 'heroku toolbelt' like opsworks utility helper.Then I saw your repo.  Think might be a foundation to work on.

Todo list I want to achieve is listed at:
 https://github.com/alex-zige/opsworks-toolbelt

Wonder do you think it would map your roadmap for your gem future releases? 
If that would work for you, we could have a chat re the priorities and best approaches etc. 
Any thoughts would be appreciated. :)

Cheers,
Alex

**Comment by eproxus** [comment]
Hi! Really sorry, somehow I missed this issue and didn't see it until now!

I actually only had a need for the SSH stuff as of now so there is no real roadmap, although the tool is written to be "easily" extendable with new sub commands and features.

Some things I do often which I'd like at some point to enable in the tool are:
- Update app settings (specifically the S3 archive that is used to deploy the app)
- Deploy an app on selected layers only (we only deploy on the app server layer, not all layers)
- Some kind of staged deployement. We often deploy incrementally on a few app servers at a time to avoid errors, this is not supported by OpsWorks so it would be nice to be able to do this via this tool (if possible).

What are your needs when it comes to such a tool?

**Comment by jsierles** [comment]
I've been adding a lot of features on my fork:

http://github.com/jsierles/opsworks

Definitely going to add staged deployment next. There's some hacky code in there now, but I plan to clean it up and move some common code into helpers.

Thanks for getting this started!

**Comment by eproxus** [comment]
If you feel the quality is up to it, I could merge it in and add you as a collaborator if you want.

**Comment by jsierles** [comment]
Adam,

Sounds good - I'd like to clean it up a bit first, i'll update then!

**Comment by eproxus** [comment]
Sure thing, you can also pull request the individual features and I'll code review them (you can still be a collaborator if you want).

**Comment by eproxus** [comment]
Archiving this repository.
